### ISSUE TITLE
define function

### ISSUE THREAD

**Issue by dalgi** [dice-group/LIMES-legacy#25]
Hi
how can I define a function in Limes? a function for define new metrics and for split entities retrived from web sites such as dblp?

**Comment by FatemeSH** [comment]
can anyone answer this question?
how can we add new function in LIMES?

**Comment by M3ssman** [comment]
As far as I know It's possible only programmatically by adopting the sources to your needs. To do this, you need to implement the Measure-Interface (as far as I remember),  put your new Measure-Function into the MeasureFactory to use it in your Configurations.

Otherwise you have to rely on those Pre-Processing build-in Functions and Metrics mentioned in the Documentation that is included in the Release Package.

**Comment by Kleanthi** [comment]
Hello and sorry for the delayed answer.
Please use the new LIMES available at: https://github.com/dice-group/LIMES
We also have included a new developer manual that will answer your question.
